stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make
  tags:
    - nix*
  artifacts:
    expire_in: 15 mins
    paths:
      - dist/sttools-customization-root.tgz

deploy:
  stage: deploy
  only:
    - master
  tags:
    - nix*
  dependencies:
    - build
  script:
    - make deploy
