stages:
  - "build"
  - "deploy"

.variables: &variables
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"
  MAVEN_GROUP: "com.stratebi.lincebi"

.variables_develop: &variables_develop
  <<: *variables
  MAVEN_REPOSITORY_ID: "lincebi-snapshots"
  MAVEN_REPOSITORY_URL: "https://repo.stratebi.com/repository/lincebi-mvn-snapshots"
  PACKAGE_VERSION_EXTRA: "${CI_COMMIT_REF_SLUG}-SNAPSHOT"

.variables_release: &variables_release
  <<: *variables
  MAVEN_REPOSITORY_ID: "lincebi-releases"
  MAVEN_REPOSITORY_URL: "https://repo.stratebi.com/repository/lincebi-mvn-releases"

.artifacts: &artifacts
  expire_in: "15 mins"
  paths:
    - "./dist/"
    - "./packages/login/dist/"
    - "./packages/home/dist/"

.cache: &cache
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "./.m2/"
    - "./node_modules/"

.regex:
  # Semantic Versioning 2.0.0 regex (from: https://github.com/npm/node-semver/).
  - &regex_version "/^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$/"

build:develop:
  stage: "build"
  variables:
    <<: *variables_develop
  script:
    - "npm install"
    - "make build"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  except:
    - *regex_version

build:release:
  stage: "build"
  variables:
    <<: *variables_release
  script:
    - "npm install"
    - "make build"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  only:
    - *regex_version

deploy:develop:mvn:
  stage: "deploy"
  dependencies:
    - "build:develop"
  variables:
    <<: *variables_develop
  script:
    - "make deploy"
  cache:
    <<: *cache
  except:
    - *regex_version

deploy:release:mvn:
  stage: "deploy"
  dependencies:
    - "build:release"
  variables:
    <<: *variables_release
  script:
    - "make deploy"
  cache:
    <<: *cache
  only:
    - *regex_version
